global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mqtt_to_prometheus'
    static_configs:
      - targets: ['mqtt_to_prometheus:8123']
    scrape_interval: 30s